# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emailService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65mailService.proto\x12\remailhandeler\"%\n\remail_request\x12\x14\n\x0c\x65mailAddress\x18\x01 \x01(\t\"0\n\x0csliced_email\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t2R\n\x0c\x45mailhandler\x12\x42\n\x05\x45mail\x12\x1c.emailhandeler.email_request\x1a\x1b.emailhandeler.sliced_emailb\x06proto3')



_EMAIL_REQUEST = DESCRIPTOR.message_types_by_name['email_request']
_SLICED_EMAIL = DESCRIPTOR.message_types_by_name['sliced_email']
email_request = _reflection.GeneratedProtocolMessageType('email_request', (_message.Message,), {
  'DESCRIPTOR' : _EMAIL_REQUEST,
  '__module__' : 'emailService_pb2'
  # @@protoc_insertion_point(class_scope:emailhandeler.email_request)
  })
_sym_db.RegisterMessage(email_request)

sliced_email = _reflection.GeneratedProtocolMessageType('sliced_email', (_message.Message,), {
  'DESCRIPTOR' : _SLICED_EMAIL,
  '__module__' : 'emailService_pb2'
  # @@protoc_insertion_point(class_scope:emailhandeler.sliced_email)
  })
_sym_db.RegisterMessage(sliced_email)

_EMAILHANDLER = DESCRIPTOR.services_by_name['Emailhandler']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMAIL_REQUEST._serialized_start=37
  _EMAIL_REQUEST._serialized_end=74
  _SLICED_EMAIL._serialized_start=76
  _SLICED_EMAIL._serialized_end=124
  _EMAILHANDLER._serialized_start=126
  _EMAILHANDLER._serialized_end=208
# @@protoc_insertion_point(module_scope)
