# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import emailService_pb2 as emailService__pb2


class EmailhandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Email = channel.unary_unary(
                '/emailhandeler.Emailhandler/Email',
                request_serializer=emailService__pb2.email_request.SerializeToString,
                response_deserializer=emailService__pb2.sliced_email.FromString,
                )


class EmailhandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Email(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailhandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Email': grpc.unary_unary_rpc_method_handler(
                    servicer.Email,
                    request_deserializer=emailService__pb2.email_request.FromString,
                    response_serializer=emailService__pb2.sliced_email.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emailhandeler.Emailhandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Emailhandler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Email(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emailhandeler.Emailhandler/Email',
            emailService__pb2.email_request.SerializeToString,
            emailService__pb2.sliced_email.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
