# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: emailService.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class EmailRequest(betterproto.Message):
    email_address: str = betterproto.string_field(1)


@dataclass
class SlicedEmail(betterproto.Message):
    username: str = betterproto.string_field(1)
    domain: str = betterproto.string_field(2)


class EmailhandlerStub(betterproto.ServiceStub):
    async def email(self) -> SlicedEmail:
        request = EmailRequest()

        return await self._unary_unary(
            "/emailhandeler.Emailhandler/Email",
            request,
            SlicedEmail,
        )
